server:
    port: 8383
spring:
    config:
        import:
            optional:file:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
    secret: ${JWT_SECRET}
    lifetime: ${JWT_LIFETIME}
