server:
    port: 8383
spring:
    config:
        import:
            optional:file:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    liquibase:
        enabled: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
    secret: ${JWT_SECRET}
    lifetime: ${JWT_LIFETIME}
credentials:
    admin:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
