
CREATE TABLE coordinates
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x  BIGINT                                  NOT NULL,
    y  INTEGER                                 NOT NULL,
    CONSTRAINT pk_coordinates PRIMARY KEY (id)
);

CREATE TABLE location
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x    DOUBLE PRECISION                         NOT NULL,
    y    DOUBLE PRECISION                         NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);