CREATE TABLE coordinates
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x  BIGINT                                  NOT NULL,
    y  INTEGER                                 NOT NULL,
    CONSTRAINT pk_coordinates PRIMARY KEY (id)
);

CREATE TABLE discipline
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                             NOT NULL,
    lecture_hours INTEGER                                  NOT NULL,
    user_id       INTEGER                                  NOT NULL,
    CONSTRAINT pk_discipline PRIMARY KEY (id)
);

CREATE TABLE lab_work
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    coordinates_id BIGINT                                   NOT NULL,
    creation_date  TIMESTAMP WITHOUT TIME ZONE,
    description    VARCHAR(255),
    difficulty     SMALLINT,
    discipline_id  INTEGER                                  NOT NULL,
    minimal_point  DOUBLE PRECISION                         NOT NULL,
    average_point  DOUBLE PRECISION                         NOT NULL,
    person_id      INTEGER                                  NOT NULL,
    user_id        INTEGER                                  NOT NULL,
    CONSTRAINT pk_labwork PRIMARY KEY (id)
);

CREATE TABLE location
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x    DOUBLE PRECISION                         NOT NULL,
    y    DOUBLE PRECISION                         NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE person
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    eye_color   SMALLINT                                 NOT NULL,
    hair_color  SMALLINT,
    location_id INTEGER,
    birthday    TIMESTAMP WITHOUT TIME ZONE,
    height      DOUBLE PRECISION                         NOT NULL,
    weight      DOUBLE PRECISION                         NOT NULL,
    user_id     INTEGER                                  NOT NULL,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(255),
    password_digest VARCHAR(255),
    salt            VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    role_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL
);

ALTER TABLE lab_work
    ADD CONSTRAINT uc_labwork_coordinates UNIQUE (coordinates_id);

ALTER TABLE person
    ADD CONSTRAINT uc_person_location UNIQUE (location_id);

ALTER TABLE discipline
    ADD CONSTRAINT FK_DISCIPLINE_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE lab_work
    ADD CONSTRAINT FK_LABWORK_ON_COORDINATES FOREIGN KEY (coordinates_id) REFERENCES coordinates (id);

ALTER TABLE lab_work
    ADD CONSTRAINT FK_LABWORK_ON_DISCIPLINE FOREIGN KEY (discipline_id) REFERENCES discipline (id);

ALTER TABLE lab_work
    ADD CONSTRAINT FK_LABWORK_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE lab_work
    ADD CONSTRAINT FK_LABWORK_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE person
    ADD CONSTRAINT FK_PERSON_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);

ALTER TABLE person
    ADD CONSTRAINT FK_PERSON_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);